sudo: false
language: node_js
node_js:
  - '0.12'
  - '4'
  - '6'
  - '8'
script: "npm run test-travis && npm run benchmark"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
